"""empty message

Revision ID: 3784a37324cc
Revises: 7e51d84433ab
Create Date: 2020-09-23 06:34:19.318686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3784a37324cc'
down_revision = '7e51d84433ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('expiry', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', name='unique_product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('product')
    # ### end Alembic commands ###
