"""empty message

Revision ID: 722fd7ed1334
Revises: 3733f3a0b49c
Create Date: 2020-09-23 07:11:58.498489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722fd7ed1334'
down_revision = '3733f3a0b49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
