"""empty message

Revision ID: 790baebfb447
Revises: dd1051e1cf86
Create Date: 2020-09-23 05:06:01.419321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790baebfb447'
down_revision = 'dd1051e1cf86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_username', 'user_v2', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_username', 'user_v2', type_='unique')
    # ### end Alembic commands ###
