"""empty message

Revision ID: 7e51d84433ab
Revises: 790baebfb447
Create Date: 2020-09-23 05:44:48.699078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e51d84433ab'
down_revision = '790baebfb447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_v2', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_v2', sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
