"""empty message

Revision ID: e5df4b164455
Revises: 56abf30b90c8
Create Date: 2020-09-20 18:15:34.513530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5df4b164455'
down_revision = '56abf30b90c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_v2', 'marketplace_id')
    op.drop_column('user_v2', 'is_trialing')
    op.drop_column('user_v2', 'plan')
    op.drop_column('user_v2', 'customer_id')
    op.drop_column('user_v2', 'has_active_subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_v2', sa.Column('has_active_subscription', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('is_trialing', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_v2', sa.Column('marketplace_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
