"""empty message

Revision ID: ef38c5c8f7fb
Revises: be37d7bf6f5d
Create Date: 2020-09-23 09:32:44.434115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef38c5c8f7fb'
down_revision = 'be37d7bf6f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
